"""Heading color helpers used by cutiepynb."""

from __future__ import annotations

import copy
import re
from typing import Any, Dict, Sequence, Tuple

DEFAULT_COLORS: Tuple[str, ...] = (
    "#6d28d9",
    "#be185d",
    "#be123c",
    "#c2410c",
    "#0e7490",
    "#047857",
)

_COLOR_IN_SPAN_RE = re.compile(
    r'(?P<prefix><span\b[^>]*\bstyle=["\'][^"\']*\bcolor\s*:\s*)'
    r'(?P<color>[^;"\']+)',
    flags=re.IGNORECASE,
)
_HEADING_LINE_RE = re.compile(r"^(?P<hashes> {0,3}#{1,6})[ \t]+(?P<body>.*)$")
_CSS_COLOR_RE = re.compile(
    r"(?:#[0-9a-fA-F]{3,8}|[A-Za-z][A-Za-z0-9-]*|"
    r"[A-Za-z][A-Za-z0-9-]*\([#A-Za-z0-9_.,% /+\-]+\))"
)


def _normalise_colors(colors: Sequence[str]) -> Tuple[str, ...]:
    palette = tuple(colors)
    if not palette:
        raise ValueError("at least one color is required")
    if any(not isinstance(color, str) or not color.strip() for color in palette):
        raise ValueError("colors must contain non-empty strings")
    if any(not _CSS_COLOR_RE.fullmatch(color.strip()) for color in palette):
        raise ValueError("colors must be safe CSS color values")
    return palette


def maquillate(
    title: str,
    level: int,
    colors: Sequence[str],
    span: bool = True,
) -> str:
    """Color ``title`` using a zero-based heading level.

    ``maquillate`` is the original helper name and remains public for backward
    compatibility. New code can generally rely on :func:`heading_html`.
    """

    palette = _normalise_colors(colors)
    color = palette[level % len(palette)]
    if span:
        return f'<span style="color: {color}">{title}</span>'
    return f' style="color: {color}">{title}'


def heading_html(title: str, level: int, colors: Sequence[str]) -> str:
    """Wrap a heading title in cutiepynb's identifiable color span."""

    if not 1 <= level <= 6:
        raise ValueError("heading level must be between 1 and 6")
    palette = _normalise_colors(colors)
    color = palette[(level - 1) % len(palette)]
    return (
        f'<span class="cutiepynb-heading" style="color: {color}">'
        f"{title}</span>"
    )


def _source_as_text(source: Any) -> str:
    return "".join(source) if isinstance(source, list) else str(source or "")


def _restore_source_type(text: str, original: Any) -> Any:
    return text.splitlines(keepends=True) if isinstance(original, list) else text


def update_heading_colors_in_document(
    document: Dict[str, Any],
    new_colors: Sequence[str],
) -> Dict[str, Any]:
    """Return a copy with existing styled heading colors replaced.

    Both current cutiepynb markup and spans generated by early releases are
    supported. The original notebook dictionary is not mutated.
    """

    palette = _normalise_colors(new_colors)
    updated_document = copy.deepcopy(document)

    for cell in updated_document.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue

        original_source = cell.get("source", "")
        lines = _source_as_text(original_source).splitlines(keepends=True)
        updated_lines = []
        for line in lines:
            match = _HEADING_LINE_RE.match(line)
            if not match:
                updated_lines.append(line)
                continue
            level = len(match.group("hashes").lstrip())
            color = palette[(level - 1) % len(palette)]
            updated_lines.append(
                _COLOR_IN_SPAN_RE.sub(
                    lambda color_match, selected=color: (
                        color_match.group("prefix") + selected
                    ),
                    line,
                    count=1,
                )
            )
        text = "".join(updated_lines)
        cell["source"] = _restore_source_type(text, original_source)

    return updated_document
